version: "3.0"

services:
  stock_service:
    build:
      context: ./backend/services/stock_service/.
      args:
        DJANGO_ENV: production
    container_name: stock_service
    environment:
      DJANGO_DEBUG: "False"
    restart: unless-stopped
    links:
      - store:redis-store
    depends_on:
      - store
    ports:
      - "8000:8000"

  job_service:
    build:
      context: ./backend/services/job_service/.
    container_name: job_service
    restart: unless-stopped
    links:
      - store:redis-store
    depends_on:
      - store
    ports:
      - "5555:5555"

  store:
    build: ./store/.
    container_name: redis-store
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: always
    volumes:
      - ./data:/data
  # frontend:
  #   build: ./frontend/.
  #   links:
  #     - backend:strapi
  #   depends_on:
  #     - backend
  #   environment:
  #     REACT_APP_BACKEND_ENDPOINT: strapi
  #   ports:
  #     - "3000:80"
