version: "3.0"

services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    restart: always
    volumes:
      - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/nginx/error.log:/etc/nginx/error_log.log
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /var/gunicorn/tmp/:/var/gunicorn/tmp/
    links:
      - store:redis-store
    depends_on:
      - stock_service
    environment:
      - ENV=development
      - APPLICATION_URL=http://stock_service:8000
    ports:
      - 80:80
      - 443:443

  stock_service:
    build:
      context: ./backend/services/stock_service/.
      args:
        DJANGO_ENV: production
    container_name: stock_service
    volumes:
      - /var/gunicorn/tmp/:/var/gunicorn/tmp/
    environment:
      DJANGO_DEBUG: "False"
    restart: unless-stopped
    links:
      - store:redis-store
    depends_on:
      - store
    ports:
      - "8000:8000"

  job_service:
    build:
      context: ./backend/services/job_service/.
    container_name: job_service
    restart: unless-stopped
    links:
      - store:redis-store
    depends_on:
      - store
    ports:
      - "5555:5555"

  store:
    build: ./store/.
    container_name: redis-store
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: always
    volumes:
      - ./data:/data
  # frontend:
  #   build: ./frontend/.
  #   links:
  #     - backend:strapi
  #   depends_on:
  #     - backend
  #   environment:
  #     REACT_APP_BACKEND_ENDPOINT: strapi
  #   ports:
  #     - "3000:80"
