# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jobs.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='jobs.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\njobs.proto\"n\n\tJobStatus\x12!\n\x06status\x18\x01 \x01(\x0e\x32\x11.JobStatus.Status\">\n\x06Status\x12\x0b\n\x07INVALID\x10\x00\x12\x0e\n\nINPROGRESS\x10\x01\x12\x0b\n\x07SUCCESS\x10\x02\x12\n\n\x06\x46\x41ILED\x10\x03\"-\n\rJobRunRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06stores\x18\x02 \x03(\t\"W\n\x0eJobRunResponse\x12\x15\n\rlaunchSuccess\x18\x01 \x01(\x08\x12\x12\n\nidentifier\x18\x02 \x01(\t\x12\x1a\n\x06status\x18\x03 \x01(\x0b\x32\n.JobStatus\"&\n\x10JobStatusRequest\x12\x12\n\nidentifier\x18\x01 \x01(\t\"/\n\x11JobStatusResponse\x12\x1a\n\x06status\x18\x01 \x01(\x0b\x32\n.JobStatus2r\n\nJobService\x12+\n\x06RunJob\x12\x0e.JobRunRequest\x1a\x0f.JobRunResponse\"\x00\x12\x37\n\x0cGetJobStatus\x12\x11.JobStatusRequest\x1a\x12.JobStatusResponse\"\x00\x62\x06proto3'
)



_JOBSTATUS_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='JobStatus.Status',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INPROGRESS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=62,
  serialized_end=124,
)
_sym_db.RegisterEnumDescriptor(_JOBSTATUS_STATUS)


_JOBSTATUS = _descriptor.Descriptor(
  name='JobStatus',
  full_name='JobStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='JobStatus.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _JOBSTATUS_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=124,
)


_JOBRUNREQUEST = _descriptor.Descriptor(
  name='JobRunRequest',
  full_name='JobRunRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='JobRunRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stores', full_name='JobRunRequest.stores', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=171,
)


_JOBRUNRESPONSE = _descriptor.Descriptor(
  name='JobRunResponse',
  full_name='JobRunResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='launchSuccess', full_name='JobRunResponse.launchSuccess', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='identifier', full_name='JobRunResponse.identifier', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='JobRunResponse.status', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=260,
)


_JOBSTATUSREQUEST = _descriptor.Descriptor(
  name='JobStatusRequest',
  full_name='JobStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifier', full_name='JobStatusRequest.identifier', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=300,
)


_JOBSTATUSRESPONSE = _descriptor.Descriptor(
  name='JobStatusResponse',
  full_name='JobStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='JobStatusResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=349,
)

_JOBSTATUS.fields_by_name['status'].enum_type = _JOBSTATUS_STATUS
_JOBSTATUS_STATUS.containing_type = _JOBSTATUS
_JOBRUNRESPONSE.fields_by_name['status'].message_type = _JOBSTATUS
_JOBSTATUSRESPONSE.fields_by_name['status'].message_type = _JOBSTATUS
DESCRIPTOR.message_types_by_name['JobStatus'] = _JOBSTATUS
DESCRIPTOR.message_types_by_name['JobRunRequest'] = _JOBRUNREQUEST
DESCRIPTOR.message_types_by_name['JobRunResponse'] = _JOBRUNRESPONSE
DESCRIPTOR.message_types_by_name['JobStatusRequest'] = _JOBSTATUSREQUEST
DESCRIPTOR.message_types_by_name['JobStatusResponse'] = _JOBSTATUSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JobStatus = _reflection.GeneratedProtocolMessageType('JobStatus', (_message.Message,), {
  'DESCRIPTOR' : _JOBSTATUS,
  '__module__' : 'jobs_pb2'
  # @@protoc_insertion_point(class_scope:JobStatus)
  })
_sym_db.RegisterMessage(JobStatus)

JobRunRequest = _reflection.GeneratedProtocolMessageType('JobRunRequest', (_message.Message,), {
  'DESCRIPTOR' : _JOBRUNREQUEST,
  '__module__' : 'jobs_pb2'
  # @@protoc_insertion_point(class_scope:JobRunRequest)
  })
_sym_db.RegisterMessage(JobRunRequest)

JobRunResponse = _reflection.GeneratedProtocolMessageType('JobRunResponse', (_message.Message,), {
  'DESCRIPTOR' : _JOBRUNRESPONSE,
  '__module__' : 'jobs_pb2'
  # @@protoc_insertion_point(class_scope:JobRunResponse)
  })
_sym_db.RegisterMessage(JobRunResponse)

JobStatusRequest = _reflection.GeneratedProtocolMessageType('JobStatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _JOBSTATUSREQUEST,
  '__module__' : 'jobs_pb2'
  # @@protoc_insertion_point(class_scope:JobStatusRequest)
  })
_sym_db.RegisterMessage(JobStatusRequest)

JobStatusResponse = _reflection.GeneratedProtocolMessageType('JobStatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _JOBSTATUSRESPONSE,
  '__module__' : 'jobs_pb2'
  # @@protoc_insertion_point(class_scope:JobStatusResponse)
  })
_sym_db.RegisterMessage(JobStatusResponse)



_JOBSERVICE = _descriptor.ServiceDescriptor(
  name='JobService',
  full_name='JobService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=351,
  serialized_end=465,
  methods=[
  _descriptor.MethodDescriptor(
    name='RunJob',
    full_name='JobService.RunJob',
    index=0,
    containing_service=None,
    input_type=_JOBRUNREQUEST,
    output_type=_JOBRUNRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetJobStatus',
    full_name='JobService.GetJobStatus',
    index=1,
    containing_service=None,
    input_type=_JOBSTATUSREQUEST,
    output_type=_JOBSTATUSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_JOBSERVICE)

DESCRIPTOR.services_by_name['JobService'] = _JOBSERVICE

# @@protoc_insertion_point(module_scope)
